language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


script:
  - hexo g
  - cd ./public
  - git init
  - git config user.name "tyxk8160"
  - git config user.email "tyxk8160@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  
branch:
  only:
  - master
env:
  global:
  - GH_REF: github.com/tyxk8160/tyxk8160.github.io.git